### ISSUE TITLE
Add AWS Systems Manager Parameter Store for AEM license to AWS resources CloudFormation stack

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/packer-aem#122]
AWS resources CF template currently only contains S3 bucket and IAM instance profile + roles.
We need to add a blank parameter store secret as part of this CloudFormation template, for the user to then populate it with the AEM license.

Here's the aws-resources CF template https://github.com/shinesolutions/packer-aem/blob/master/templates/cloudformation/aws-resources.yaml

Naming convention wise, please keep them consistent to AEM AWS Stack Builder's CF templates https://github.com/shinesolutions/aem-aws-stack-builder/tree/master/templates/cloudformation

**Comment by phillipinman** [comment]
Hi cliff,

Just curious regarding the naming convention if

AEMLicense would be an acceptable naming parameter?

**Comment by cliffano** [comment]
This is done in https://github.com/shinesolutions/packer-aem/pull/123
