### ISSUE TITLE
Make repository_volume_device configurable

### ISSUE THREAD

**Issue by veldotshine** [shinesolutions/packer-aem#127]
In order to support environments where ` /dev/xvdb`, `/dev/xvdc` are already used, we have to allow configurable device mapping per component.
At present, author-publish-dispatcher defaults to use xvdb and xvdc. This needs to consume the config from user config YAML.

Configure these values, in such a way it can be passed from OpenCloud-config repo

**Comment by cliffano** [comment]
Done. To be included in release 3.8.0 .
