### ISSUE TITLE
Ensure aem.ks has enough permission  

### ISSUE THREAD

**Issue by veldotshine** [shinesolutions/packer-aem#129]
Insufficient permissions to keystore file doesn't allow to access the crx services in https port for author and publish . This occurs on environment with CIS benchmark.

With CIS:
[ec2-user@ip-10-215-208-11 ~]$ sudo ls -lrt /opt/aem/publish/crx-quickstart/ssl/
-rw-r-----. 1 root root 3958 Feb 21 15:37 aem.ks
[ec2-user@ip-10-215-208-11 ~]$ sudo ls -lrt /opt/aem/author/crx-quickstart/ssl/
-rw-r-----. 1 root root 3958 Feb 21 15:37 aem.ks

Without CIS:
[ec2-user@ip-10-215-208-11 ~]$ ls -lrt /opt/aem/author/crx-quickstart/ssl/
-rwxr-xr-x. 1 root root 3958 Feb 21 14:54 aem.ks
[ec2-user@ip-10-215-208-11 ~]$ ls -lrt /opt/aem/publish/crx-quickstart/ssl/
-rwxr-xr-x. 1 root root 3958 Feb 21 14:54 aem.ks

The fix should be on changing hte ownership of the keystore file so it's owned by author/publish user depending on the component, and not root.

**Comment by cliffano** [comment]
Done. To be included in release 3.8.0 .
