### ISSUE TITLE
AEM Content upload via package manager doesn't work due to insufficient permission to temp folder 

### ISSUE THREAD

**Issue by veldotshine** [shinesolutions/packer-aem#130]
In certain environment where CIS benchmark is applied, AEM cannot simply use the default temporary directory (/tmp on linux) which causes AEM package upload to fail.

We need to introduce a configurable temporary directory for AEM to use. Try setting this on java.io.tmpdir .
Please make sure that java.io.tmpdir is mandatory, i.e. when we pass JVM OPTS to puppet-aem, java.io.tmpdir won't be removed by user configuration, it can be overwritten, but not entirely removed.

**Comment by cliffano** [comment]
Closing this ticket since this turns out to be a non-issue.
The temp directory can still live under `/tmp/subdir` as long as the `subdir` has the correct ownership/permission .
