### ISSUE TITLE
Chaos Monkey fails to start on a CIS benchmark hardened environment

### ISSUE THREAD

**Issue by veldotshine** [shinesolutions/packer-aem#133]
Due to CIS requirement with reduced access to 
`/opt/netflix/simianarmy.war` for service user `simianarmy` user, we need to change the ownership of `/opt/netflix/simianarmy.war` to the service user itself (i.e. `simianarmy`).

The organisation directory `/opt/netflix` itself needs to still be owned by root and have permission mode consistent to `/opt/aem/` 's permission on author or publish component.

**Comment by cliffano** [comment]
This issue is not a Packer AEM issue.
Replaced by https://github.com/shinesolutions/aem-aws-stack-builder/issues/268 .
