### ISSUE TITLE
Orchestrator fails to start on a CIS benchmark hardened environment

### ISSUE THREAD

**Issue by veldotshine** [shinesolutions/packer-aem#134]
Due to CIS requirement with reduced access to 
`/opt/shinesolutions/aem-orchestrator` for service user `aem-orchestrator` user, we need to change the ownership of `/opt/shinesolutions/aem-orchestrator` to the service user itself (i.e. `aem-orchestrator`).

The organisation directory `/opt/shinesolutions` itself needs to be owned by root and have permission mode consistent to `/opt/aem/` 's permission on author or publish component.

**Comment by cliffano** [comment]
This is not a Packer AEM specific issue.
Replaced by https://github.com/shinesolutions/aem-aws-stack-builder/issues/269 .
