### ISSUE TITLE
Upgrade Packer AEM Hiera to version 5

### ISSUE THREAD

**Issue by phillipi-shinesolutions** [shinesolutions/packer-aem#135]
Due to requirements for a puppet module to read AWS SSM parameters we need to update Puppet's Hiera Version to 5. 

Link to module: https://github.com/luizvasconceloss/hiera-ssm-paramstore

Currently the scope of the work is just the heria.yaml file but the entire packer-aem project will need to be checked for any older hiera() lookups.

This currently blocks issue #125

**Comment by cliffano** [comment]
Done. To be included in release 3.8.0 .
