### ISSUE TITLE
Missing region in aws_ssm_parameter_store module

### ISSUE THREAD

**Issue by rJunx** [shinesolutions/packer-aem#161]
TASK [Create AWS SSM License Secure String Parameter] **************************
fatal: [127.0.0.1]: FAILED! => changed=false 
  msg: The aws_ssm_parameter_store module requires a region and none was found in configuration, environment variables or module parameters

**Comment by cliffano** [comment]
Done. The fix was included in release 4.6.0 .
https://github.com/shinesolutions/packer-aem/commit/1d690d8930fd021a870acb0036f80f2b4150237c
