### ISSUE TITLE
Move dispatcher docroot to separate volume

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/packer-aem#30]
Dispatcher AMI currently has Apache docroot on the root volume.
Considering it contains content, consistent to author and publish AMIs' repository, it should be moved to a separate volume which can be configured to have larger size.

The dispatcher docroot can also be considered a state to replicate during scaling process, or to restore to during recovery.

**Comment by hoomaan-kh** [comment]
it is been done via `9bd806f1d9c7dd08fc151932af607b958d50959d` commit
