### ISSUE TITLE
NewRelic should be removed from packer-aem core

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/packer-aem#38]
newrelic-infra package is currently provisioned in init.pp .
NewRelic is user-specific and if user wants to use it, then it should be baked into user's base AMI (and any provisioning during stack creation time can live in custom stack provisioner).

packer-aem's scope is to support AWS and potentially other cloud providers in the future, but not various other external services.

**Comment by ovlords** [comment]
Done.
