### ISSUE TITLE
cloudwatch_writer.py needs to be updated to get collectd running

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/packer-aem#58]
Due to some changes in the 

cloudwatch.modules.flusher

module. flusher accepts now 3 arguments and not 2 anymore: 

Jan 19 12:08:56 ip-10-0-13-85 collectd[14688]: [AmazonCloudWatchPlugin][cloudwatch.modules.configuration.confighelper] Fetched asg name as NONE
Jan 19 12:08:56 ip-10-0-13-85 collectd[14688]: Unhandled python exception in init callback: TypeError: __init__() takes exactly 3 arguments (2 given)
Jan 19 12:08:56 ip-10-0-13-85 collectd[14688]: Traceback (most recent call last):
Jan 19 12:08:56 ip-10-0-13-85 collectd[14688]:  File "/opt/collectd-cloudwatch/src/cloudwatch_writer.py", line 20, in aws_init#012    flusher = Flusher(config)
Jan 19 12:08:56 ip-10-0-13-85 collectd[14688]: TypeError: __init__() takes exactly 3 arguments (2 given)
Jan 19 12:08:56 ip-10-0-13-85 collectd[14688]: plugin_dispatch_values: No write callback has been registered. Please load at least one output plugin, if you want the collected data to be stored.
Jan 19 12:08:56 ip-10-0-13-85 collectd[14688]: Available write targets: [none]
Jan 19 12:08:56 ip-10-0-13-85 collectd[14688]: Filter subsystem: Built-in target `write': Dispatching value to all write plugins failed with status 2 (ENOENT). Most likely this means you didn't load any write plugins.
Jan 19 12:08:56 ip-10-0-13-85 collectd[14688]: Available write targets: [none]
Jan 19 12:08:56 ip-10-0-13-85 collectd[14688]: Initialization complete, entering read-loop.
Jan 19 12:08:56 ip-10-0-13-85 collectd[14688]: Available write targets: [none]
Jan 19 12:08:56 ip-10-0-13-85 collectd[14688]: Available write targets: [none]

**Comment by mbloch1986** [comment]
Change was made with this commit:

https://github.com/awslabs/collectd-cloudwatch/commit/205cd27b09d8e44d3ceaf44f747ce12f9236d59b#diff-590d383db1bf47fc9a6707f9707cf34a

**Comment by cliffano** [comment]
Done. To be included in v2.3.0 .
