### ISSUE TITLE
Add Puppet installation for amazon-linux

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/packer-aem#60]
amazon-linux bash provisioner is currently just a placeholder https://github.com/shinesolutions/packer-aem/blob/master/provisioners/bash/amazon-linux.sh .

This needs to be made on-par with RHEL7. https://github.com/shinesolutions/packer-aem/blob/master/provisioners/bash/rhel7.sh 

Amazon Linux 2 has been released, the PR that Ramses provided attempts to use Amazon Linux 2 but not yet done. The aim is to install Puppet5 using systemd, which was first introduced in Amazon Linux 2.

**Comment by pzurzolo** [comment]
What I've found:
1. Some packages are not named as expected (e.g. Python27, python-pip, collectd-python).
2. Some packages are not available by default in the pre-configured repository (e.g python27-cheetah, collectd-python) and will need to be installed by other means.
3. HDD device names have changed from /dev/sda1, /dev/sdb to /dev/xvda, /dev/xvdb format.

Changes I've had to make so far:
1. Updated the ami in example config examples/user-config/os-amazon-linux2.yaml
2. Included a new hiera config file to override some vars for Amazon Linux 2
3. Modified the base puppet file to include an if-else control on what packages to install for amazon linux 2 (likely temporary till we can find an appropriate way to install some packages)
4. Modified launch_block_device_mappings to update HDD device name mappings (see findings above).

**Comment by pzurzolo** [comment]
Found an AWS doco which outlines how to add EPEL repo to an Amazon Linux 2 instance: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/add-repositories.html.

**Comment by pzurzolo** [comment]
Also, @cliffano found this forum discussion which outlines that Amazon Linux 2 does not have EPEL repo installed by default, but it is possible to use: https://forums.aws.amazon.com/thread.jspa?threadID=271156

**Comment by pzurzolo** [comment]
new issue discovered with ruby-gems. /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/train-0.32.0/lib/train/platforms/detect/helpers/os_linux.rb:16:in `redhatish_version': undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by pzurzolo** [comment]
Issue with httpd package install when trying a aws-dispatcher build:
Error: Execution of '/bin/yum -e 0 -y install httpd24' returned 1: Loaded plugins: langpacks, priorities, update-motd

Likely the wrong package name for Amazon Linux 2, but will investigate.

**Comment by cliffano** [comment]
The leftover issues are:
- investigate why cloudwatch logs service status inspec check still fails on amazon-linux2
- investigate why cq.pid inspec check also fails on amazon-linux2 (this is currently commented out)

**Comment by michaeldiender-shinesolutions** [comment]
inspec 0.32 doesn't support amazon linux 2. attempts to use upstart to test the service, but fails.

puppet-aem: https://github.com/shinesolutions/puppet-aem/blob/master/manifests/service.pp#L32 configures the init.d service script. but it is the systemd script that manages the cq.pid file.

**Comment by cliffano** [comment]
Amazon Linux 2 support has been released as part of version 3.5.0 .
