### ISSUE TITLE
Set Proxy configuration for SSM Agent Service

### ISSUE THREAD

**Issue by ovlords** [shinesolutions/packer-aem#64]
In order to let the running SSM Agent daemon on linux contact the AWS API behind a proxy server, we need to add a Manifest which configured the proxy setting for the SSM Agent Daemon.

As described here:

https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-proxy-with-ssm-agent.html

The first test shows, that the configuration file for systemd seems to be the best solution.

**Comment by ovlords** [comment]
This appears to be partly available in the SSM_Module.  However, it only supports one environment variable for now.

**Comment by cliffano** [comment]
Proxy configuration support has been added to 2.4.0 .
